// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: swissknife.proto

package swissknife

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvHexaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *ConvHexaReq) Reset() {
	*x = ConvHexaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swissknife_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvHexaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvHexaReq) ProtoMessage() {}

func (x *ConvHexaReq) ProtoReflect() protoreflect.Message {
	mi := &file_swissknife_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvHexaReq.ProtoReflect.Descriptor instead.
func (*ConvHexaReq) Descriptor() ([]byte, []int) {
	return file_swissknife_proto_rawDescGZIP(), []int{0}
}

func (x *ConvHexaReq) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ConvHexaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ConvHexaRes) Reset() {
	*x = ConvHexaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swissknife_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvHexaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvHexaRes) ProtoMessage() {}

func (x *ConvHexaRes) ProtoReflect() protoreflect.Message {
	mi := &file_swissknife_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvHexaRes.ProtoReflect.Descriptor instead.
func (*ConvHexaRes) Descriptor() ([]byte, []int) {
	return file_swissknife_proto_rawDescGZIP(), []int{1}
}

func (x *ConvHexaRes) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ConvBase64Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *ConvBase64Req) Reset() {
	*x = ConvBase64Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swissknife_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvBase64Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvBase64Req) ProtoMessage() {}

func (x *ConvBase64Req) ProtoReflect() protoreflect.Message {
	mi := &file_swissknife_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvBase64Req.ProtoReflect.Descriptor instead.
func (*ConvBase64Req) Descriptor() ([]byte, []int) {
	return file_swissknife_proto_rawDescGZIP(), []int{2}
}

func (x *ConvBase64Req) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ConvBase64Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ConvBase64Res) Reset() {
	*x = ConvBase64Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swissknife_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvBase64Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvBase64Res) ProtoMessage() {}

func (x *ConvBase64Res) ProtoReflect() protoreflect.Message {
	mi := &file_swissknife_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvBase64Res.ProtoReflect.Descriptor instead.
func (*ConvBase64Res) Descriptor() ([]byte, []int) {
	return file_swissknife_proto_rawDescGZIP(), []int{3}
}

func (x *ConvBase64Res) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_swissknife_proto protoreflect.FileDescriptor

var file_swissknife_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x77, 0x69, 0x73, 0x73, 0x6b, 0x6e, 0x69, 0x66, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x76, 0x48, 0x65, 0x78, 0x61, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x76, 0x48,
	0x65, 0x78, 0x61, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x25,
	0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x76, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x27, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x76, 0x42, 0x61, 0x73,
	0x65, 0x36, 0x34, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x69,
	0x0a, 0x0d, 0x53, 0x77, 0x69, 0x73, 0x73, 0x6b, 0x6e, 0x69, 0x66, 0x65, 0x53, 0x76, 0x63, 0x12,
	0x28, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x76, 0x48, 0x65, 0x78, 0x61, 0x12, 0x0c, 0x2e, 0x43, 0x6f,
	0x6e, 0x76, 0x48, 0x65, 0x78, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x43, 0x6f, 0x6e, 0x76,
	0x48, 0x65, 0x78, 0x61, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e,
	0x76, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x12, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x42, 0x61,
	0x73, 0x65, 0x36, 0x34, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x42, 0x61,
	0x73, 0x65, 0x36, 0x34, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b,
	0x73, 0x77, 0x69, 0x73, 0x73, 0x6b, 0x6e, 0x69, 0x66, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_swissknife_proto_rawDescOnce sync.Once
	file_swissknife_proto_rawDescData = file_swissknife_proto_rawDesc
)

func file_swissknife_proto_rawDescGZIP() []byte {
	file_swissknife_proto_rawDescOnce.Do(func() {
		file_swissknife_proto_rawDescData = protoimpl.X.CompressGZIP(file_swissknife_proto_rawDescData)
	})
	return file_swissknife_proto_rawDescData
}

var file_swissknife_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_swissknife_proto_goTypes = []interface{}{
	(*ConvHexaReq)(nil),   // 0: ConvHexaReq
	(*ConvHexaRes)(nil),   // 1: ConvHexaRes
	(*ConvBase64Req)(nil), // 2: ConvBase64Req
	(*ConvBase64Res)(nil), // 3: ConvBase64Res
}
var file_swissknife_proto_depIdxs = []int32{
	0, // 0: SwissknifeSvc.ConvHexa:input_type -> ConvHexaReq
	2, // 1: SwissknifeSvc.ConvBase64:input_type -> ConvBase64Req
	1, // 2: SwissknifeSvc.ConvHexa:output_type -> ConvHexaRes
	3, // 3: SwissknifeSvc.ConvBase64:output_type -> ConvBase64Res
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_swissknife_proto_init() }
func file_swissknife_proto_init() {
	if File_swissknife_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_swissknife_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvHexaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swissknife_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvHexaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swissknife_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvBase64Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swissknife_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvBase64Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_swissknife_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swissknife_proto_goTypes,
		DependencyIndexes: file_swissknife_proto_depIdxs,
		MessageInfos:      file_swissknife_proto_msgTypes,
	}.Build()
	File_swissknife_proto = out.File
	file_swissknife_proto_rawDesc = nil
	file_swissknife_proto_goTypes = nil
	file_swissknife_proto_depIdxs = nil
}
